#!/bin/sh

if [ -z $1 ]
then
    echo "No arguments given!"
else
   if [ $# -gt 1 ]
   then
      while (( $# ))
      do
        open "http://www.cantonese.sheik.co.uk/dictionary/characters/${1}/"
        shift 1
      done
      echo "That was all!"
  else
    for i in $(seq 1 ${#1}); do
       open "http://www.cantonese.sheik.co.uk/dictionary/characters/${1:i-1:1}/"
       echo "${1:i-1:1}"
    done
    echo "That was all!"
   fi
fi

